## ==========lidar config==========
# Detect distance and angle range
range_min : 1.5
range_max : 16.0
angle_min : -180.0
angle_max : 180.0
height_min : 0.0
height_max : 0.0
# Robot itself
robot_x_max : 0.3
robot_x_min : -0.3
robot_y_max : 0.2
robot_y_min : -0.2
robot_z_max : 0
robot_z_min : -0.3
# Map metadata
#robot_frame : "base_link"
robot_frame : "laser_frame"
map_resolution : 0.13
obs_size : 0.1
dilating_size : 2
map_size : 60

